#!/system/bin/sh
## Post boot commands by gabrielgagz ##

# Setting permissions
chmod 644 /sys/block/mmcblk0/queue/scheduler
chmod 644 /sys/block/mmcblk0/queue/read_ahead_kb
chmod 644 /sys/module/lowmemorykiller/parameters/minfree

# Changing IO Scheduler
echo fiops > /sys/block/mmcblk0/queue/scheduler

# Start ADB over tcp
setprop service.adb.tcp.port 5555
stop adbd
start adbd

# Tweaks
echo "1024" > /sys/block/mmcblk0/queue/read_ahead_kb
echo "9706,14559,29118,48530,67942,72795" > /sys/module/lowmemorykiller/parameters/minfree

# Enable faux123 intelliplug in performance mode
echo "1" > /sys/module/intelli_plug/parameters/intelli_plug_active
echo "1" > /sys/module/intelli_plug/parameters/nr_run_profile_sel
echo "4" > /sys/module/intelli_plug/parameters/nr_run_hysteresis
